import type { Product, Testimonial } from '@/types'

export const SITE_NAME = 'AKINORIO'
export const SITE_URL = 'https://akinorio.com'
export const SITE_DESCRIPTION = '何をつけるかより、何をやめるか。ミトコンドリア×ケイ素の力で、肌のOSを初期化する引き算のスキンケア。'
export const LINE_URL = 'https://lin.ee/Sa4uQuI'
export const FREE_SHIPPING_THRESHOLD = 10000
export const SHIPPING_FEE = 600

export const PRODUCTS: Product[] = [
  {
    id: '1', slug: 'mitochondria', name: 'ミトコンドリアのちから', subtitle: '細胞美容液',
    description: '原料メーカーが「これだけの配合量は美容液と呼んでください」と言った一本。\nファンデーションも化粧水もいらない。ダブル洗顔も不要。\n最終的にこの一本で済む素肌へ導くために生まれた、引き算のスキンケアの核心。\nミトコンドリアとケイ素の力で、細胞が自ら美しくなる力を呼び覚まします。',
    category: 'single', price: 13200, volume: '50g',
    ingredients: 'シリカ水、スクワラン、ホホバ種子油、ミトコンドリア活性成分配合',
    usageDuration: '約3ヶ月',
    features: ['ミトコンドリア活性化テクノロジー', 'ケイ素（シリカ）配合', 'パラベンフリー・アルコールフリー'],
    skinConcerns: ['乾燥', '毛穴', 'シミ・くすみ', 'ハリ・たるみ', '敏感肌'],
    image: '/images/products-bg-hik/mitokondria.png', images: [], sortOrder: 1, isActive: true,
    hikImage: '/images/products-bg-hik/mitokondria.png',
    howToUse: '洗顔後、適量を手に取り顔全体になじませてください。目元・口元など気になる部分には重ねづけが効果的です。',
    shopifyVariantId: '62656776241523',
  },
  {
    id: '2', slug: 'herb', name: 'ハーブのちから', subtitle: '肌育エッセンス',
    description: '自然の生命力が宿るハーブの滴。\n肌の土台を整え、硬くなった角質をやさしく解きほぐすことで、\n次に使う美容成分の浸透を劇的に高めます。',
    category: 'single', price: 8800, volume: '30ml',
    usageDuration: '約3ヶ月',
    ingredients: '', features: [], skinConcerns: ['乾燥', '毛穴'],
    image: '/images/products-bg-hik/herb.png', images: [], sortOrder: 2, isActive: true,
    hikImage: '/images/products-bg-hik/herb.png',
    howToUse: '洗顔後、化粧水のように適量を顔全体にやさしくなじませてください。',
    shopifyVariantId: '62656776307059',
  },
  {
    id: '6', slug: 'cleansing', name: 'クリアクリスタルクレンジング', subtitle: '摩擦ゼロのメイク落とし',
    description: 'ダブル洗顔という「余計な儀式」を終わらせるクレンジング。\nメイクも毛穴汚れも、するんと落とす。落とすたびに肌が整っていきます。',
    category: 'single', price: 6600, volume: '180ml',
    ingredients: 'シリカ水、ヤシ油脂肪酸、グリセリン、ミトコンドリア活性成分配合',
    features: ['ジェルタイプで肌に優しい', 'ダブル洗顔不要', '毛穴汚れもすっきり'],
    skinConcerns: ['毛穴', '敏感肌'],
    image: '/images/products-bg-hik/cleansing.png', images: [], sortOrder: 3, isActive: true,
    hikImage: '/images/products-bg-hik/cleansing.png',
    howToUse: '乾いた手でメイクなじませ、少量の水でなじませてからぬるま湯で洗い流してください。',
    shopifyVariantId: '62656776339827',
  },
  {
    id: '3', slug: 'kihada', name: '輝肌（キハダ）', subtitle: '極上艶ヴェール',
    description: '呼び覚ました肌本来のチカラを、極上のヴェールで閉じ込める。\n与えすぎない「引き算」が完成させる、圧倒的な艶と透明感をご体感ください。',
    category: 'single', price: 11000, volume: '50g',
    usageDuration: '約3ヶ月',
    ingredients: '', features: [], skinConcerns: ['シミ・くすみ', '乾燥'],
    image: '/images/products-bg-hik/kihada.png', images: [], sortOrder: 4, isActive: true,
    hikImage: '/images/products-bg-hik/kihada.png',
    howToUse: 'スキンケアの最後に適量を手に取り、顔全体にやさしくなじませてください。',
    shopifyVariantId: '62656776372595',
  },
  {
    id: '4', slug: 'balm', name: '金の糸クリーム（クリアクリスタルバーム）', subtitle: '究極の細胞覚醒バーム',
    description: '最上級の保湿と細胞活性を両立させた奇跡のバーム。\n夜のスキンケアの最後に塗るだけで、翌朝の肌が見違えるように生まれ変わります。',
    category: 'single', price: 22000, volume: '100g',
    usageDuration: '約4〜6ヶ月',
    ingredients: '', features: [], skinConcerns: ['ハリ・たるみ', '乾燥'],
    image: '/images/products-bg-hik/kinnoito.png', images: [], sortOrder: 5, isActive: true,
    hikImage: '/images/products-bg-hik/kinnoito.png',
    howToUse: 'アイクリーム・ネッククリーム・ハンドクリームとして。1日に何度でもお使いいただけます。',
    shopifyVariantId: '62656776405363',
  },
  {
    id: '5', slug: 'serum', name: 'クリアクリスタルセラム', subtitle: '高濃度美容液',
    description: '極限までピュアな状態で抽出された高濃度な美容液。\n水のように軽やかに肌の奥深くへ浸透し、かつてないハリと弾力を目覚めさせます。',
    category: 'single', price: 11000, volume: '200ml',
    usageDuration: '約3ヶ月',
    ingredients: '水、グリセリン、BG、ペンチレングリコール、乳酸Na、クラドシホンノバエカレドニアエ多糖体、加水分解コラーゲン、サッカロミセスセレビシアエキス、ナットウガム、アルギニン、トリ（カプリル酸/カプリン酸）グリセリル、セラミドEOP、セラミドNG、セラミドNP、セラミドAP、フィトステロールズ、水添レシチン、PEG-40水添ヒマシ油、フェノキシエタノール',
    features: [], skinConcerns: ['シミ・くすみ', 'ハリ・たるみ'],
    image: '/images/products-bg-hik/serum.png', images: [], sortOrder: 6, isActive: true,
    hikImage: '/images/products-bg-hik/serum.png',
    howToUse: '洗顔後、化粧水の前に適量を顔全体になじませてください。',
    shopifyVariantId: '62656776438131',
  },
  {
    id: '7', slug: 'uv', name: 'クリアクリスタルスキンベースUV', subtitle: '美容液UVベース',
    description: '紫外線から肌を確実に守りながら、日中もスキンケアし続ける新感覚のUVベース。\n負担を一切感じさせない極上の軽さです。',
    category: 'single', price: 5500, volume: '30g',
    usageDuration: '約3ヶ月',
    ingredients: '', features: [], skinConcerns: ['シミ・くすみ', '敏感肌'],
    image: '/images/products-bg-hik/uv.png', images: [], sortOrder: 7, isActive: true,
    hikImage: '/images/products-bg-hik/uv.png',
    howToUse: 'スキンケアの最後に適量を顔全体に伸ばし、日焼け止めとして使用してください。',
    shopifyVariantId: '62656776470899',
  },
  {
    id: '12', slug: 'starter-set', name: '輝魔女セット', subtitle: 'ミトコンドリアのちから＋ハーブのちから',
    description: '引き算スキンケアの入口として、最も多くの方に選ばれている2本セット。\nミトコンドリアのちから（細胞美容液）とハーブのちから（肌育エッセンス）が揃うことで、\n肌本来の力を呼び覚ます引き算ルーティンがはじまります。\n\n引き算ケアの真骨頂\nこの２つのセットで肌本来のちからを引き上げ、護る',
    category: 'set', price: 19800, volume: '2本セット',
    usageDuration: '約3ヶ月',
    ingredients: '',
    features: ['ミトコンドリア活性化テクノロジー', 'ケイ素（シリカ）配合', 'ハーブ由来11種配合', 'パラベンフリー・アルコールフリー'],
    skinConcerns: ['乾燥', '毛穴', 'シミ・くすみ', 'ハリ・たるみ', '敏感肌'],
    image: '/images/products/starterset.png', images: [], sortOrder: 7.5, isActive: true,
    hikImage: '/images/products-bg-hik/starterset.png',
    howToUse: '洗顔後、ハーブのちからを顔全体になじませてから、ミトコンドリアのちからを重ねてください。',
    shopifyVariantId: '62647648551283',
  },
  {
    id: '8', slug: 'kimajyoset', name: '輝魔女セット', subtitle: '基本の引き算セット',
    description: '肌のOSを初期化するための、基本のステップが揃ったセット。\nこれだけで、あなたのスキンケアは完了します。',
    category: 'set', price: 22000, volume: '1セット',
    ingredients: '', features: [], skinConcerns: ['乾燥', '毛穴', '敏感肌'],
    image: '/images/products-bg-hik/kimajyoset.png', images: [], sortOrder: 8, isActive: true,
    hikImage: '/images/products-bg-hik/kimajyoset.png',
    howToUse: 'セット内各アイテムの使用方法に従ってご使用ください。',
    shopifyVariantId: '62656776503667',
  },
  {
    id: '9', slug: 'kagayaki-majo', name: '輝魔女セット', subtitle: '極上のエイジングケア',
    description: 'ミトコンドリアのちから、ハーブのちから、輝肌Kihadaがセットに。\n本来の美しさを呼び覚ます、ブランド最高峰の組み合わせ。',
    category: 'set', price: 33000, volume: '1セット',
    ingredients: '', features: [], skinConcerns: ['シミ・くすみ', 'ハリ・たるみ', '乾燥'],
    image: '/images/products-bg-hik/allseries_fine.png', images: [], sortOrder: 9, isActive: true,
    hikImage: '/images/products-bg-hik/allseries_fine.png',
    howToUse: 'セット内各アイテムの使用方法に従ってご使用ください。',
    shopifyVariantId: '62656776536435',
  },
  {
    id: '10', slug: 'premium', name: '輝魔女プレミアム', subtitle: '最上級コンプリート',
    description: 'アキノリオの全ての真価を余すところなく体験できる、最上級のフルセット。\n揺るぎない自信と究極の美肌をあなたに。',
    category: 'set', price: 38500, volume: '1セット',
    ingredients: '', features: [], skinConcerns: ['シミ・くすみ', 'ハリ・たるみ', '乾燥'],
    image: '/images/products-bg-hik/allseries_fine.png', images: [], sortOrder: 10, isActive: true,
    hikImage: '/images/products-bg-hik/allseries_fine.png',
    howToUse: 'セット内各アイテムの使用方法に従ってご使用ください。',
    shopifyVariantId: '62656776569203',
  },
  {
    id: '11', slug: 'perfume', name: 'Perfume（美容液混合シャンプー）', subtitle: 'ノンシリコン・2本セット',
    description: '美容成分と超高級ケラチンで洗い上げる贅沢。\nトリートメントもボディソープも捨てる、新時代の引き算ケア。\n頭皮のたるみはお顔のたるみ。着目したのは「一つなぎの肌」。\n最終的にこの一本で全身が潤う、極上のスキンケア処方です。\n「しっとりまとまるのに、ペタッとしない」\nシルクの力で、ふんわりと軽やかな美しいツヤ髪へと導きます。',
    category: 'set', price: 9240, volume: '250ml×2本',
    usageDuration: '—',
    ingredients: '水・ココイルメチルタウリンタウリンNａ・コカミドプロピルベタイン・ココイルアラニンTEA・ラウロイルメチルアラニンNａ・塩化Ｎａ・サッカロミセスセレビシアエエキス・ホスファチジルコリン・チシマザサ水・加水分解ケラチン（羊毛）・加水分解ケラチン（カシミヤヤギ）・（ジヒドロキシメチルシリルプロポキシ）ヒドロキシプロピル加水分解シルク・（加水分解シルク/ＰＧプロピルメチルシランジオール）クロスポリマー・グリチルリチン酸2Ｋ・コカミドＤＥＡ・ポリクオタニウム-10・ポリクオタニウム-61・ジステアリン酸ＰＥＧ-190・ヤシ油脂肪酸ＰＥＧ-7グリセチル・ココイルアルギニンエチルＰＣＡ・クエン酸・アルギニン・ＢＧ・グリセリン・ペンチレングリコール・カプリリルグリコール・フェノキシエタノール・香料',
    features: ['ワイン酵母・ケラチン・シルク配合', 'トリートメント不要', '必ず2本セットで販売'],
    skinConcerns: ['抜け毛', 'パサつき', 'ダメージ補修'],
    image: '/images/products-bg-hik/shampoo.png', images: [], sortOrder: 11, isActive: true,
    hikImage: '/images/products-bg-hik/shampoo.png',
    howToUse: '適量を手に取り、髪全体になじませて洗い流してください。トリートメント不要です。',
    shopifyVariantId: '62656776634739',
  }
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'M.T',
    age: 52,
    skinConcern: 'ハリ・たるみ',
    content: '引き算を始めて1ヶ月。朝、鏡を見て涙が出ました。何十年も「足す」ことばかりしていた自分が恥ずかしくなるほど、肌が生き返っていた。もっと早く出会いたかった。この感動を、同じ悩みを持つ友人にも伝えました。',
    rating: 5,
    productName: 'ミトコンドリアのちから 美容液',
  },
  {
    id: '2',
    name: 'K.S',
    age: 45,
    skinConcern: '毛穴',
    content: '長年の毛穴の悩みが、引き算を始めて3ヶ月で嘘のように落ち着きました。化粧水を重ねて、美容液を重ねて、クリームを重ねて。あの「足し算の日々」は一体何だったのか。救われた気持ちです。友人にも教えたくて、もう3人に紹介しました。',
    rating: 5,
    productName: 'ミトコンドリアのちから 美容液',
  },
  {
    id: '3',
    name: 'Y.N',
    age: 38,
    skinConcern: '敏感肌',
    content: 'アトピー体質で、何を塗っても赤くなる肌でした。皮膚科で処方された薬すら合わないこともあった。でもアキノリオだけは違った。全く刺激がなく、肌が本来の力を取り戻していくのを感じました。本当に救われました。',
    rating: 5,
    productName: 'ミトコンドリアのちから 美容液',
  },
  {
    id: '4',
    name: 'R.M',
    age: 61,
    skinConcern: 'シミ・くすみ',
    content: '60歳を過ぎて「もう何をしても」と諦めていました。でも引き算を始めてから、肌が自ら明るさを取り戻していく。ファンデーションなしで外出できる日が来るなんて。娘に「お母さん、肌きれいになった」と言われた時、泣きそうになりました。',
    rating: 5,
    productName: 'ミトコンドリアのちから 美容液',
  },
]

export const PREFECTURES = [
  '北海道', '青森県', '岩手県', '宮城県', '秋田県', '山形県', '福島県',
  '茨城県', '栃木県', '群馬県', '埼玉県', '千葉県', '東京都', '神奈川県',
  '新潟県', '富山県', '石川県', '福井県', '山梨県', '長野県',
  '岐阜県', '静岡県', '愛知県', '三重県',
  '滋賀県', '京都府', '大阪府', '兵庫県', '奈良県', '和歌山県',
  '鳥取県', '島根県', '岡山県', '広島県', '山口県',
  '徳島県', '香川県', '愛媛県', '高知県',
  '福岡県', '佐賀県', '長崎県', '熊本県', '大分県', '宮崎県', '鹿児島県', '沖縄県',
]
