import type { Product, Testimonial } from '@/types'

export const SITE_NAME = 'AKINORIO'
export const SITE_URL = 'https://akinorio.com'
export const SITE_DESCRIPTION = '細胞レベルに着目した引き算のスキンケア。ミトコンドリア×ケイ素の科学で、あなた本来の輝きを。'
export const LINE_URL = 'https://lin.ee/qF2bQ2v'
export const FREE_SHIPPING_THRESHOLD = 10000
export const SHIPPING_FEE = 600

export const PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'serum',
    name: 'ミトコンドリアのちから',
    subtitle: '細胞美容液',
    description: 'ミトコンドリアとケイ素の力で、細胞レベルからお肌を目覚めさせる美容液。引き算のスキンケアの主役です。洗顔後、化粧水の前にお使いください。わずか1滴で、お肌の奥深くまで届く実感をお楽しみいただけます。',
    category: 'single',
    price: 13200,
    subscriptionPrice: 11880,
    subscriptionDiscountPct: 10,
    volume: '50g',
    usageDuration: '約3ヶ月',
    ingredients: 'シリカ水、スクワラン、ホホバ種子油、ミトコンドリア活性成分配合',
    features: [
      'ミトコンドリア活性化テクノロジー',
      'ケイ素（シリカ）配合',
      'パラベンフリー・アルコールフリー',
      '敏感肌にも使える低刺激処方',
      '1本で約3ヶ月使用可能',
    ],
    skinConcerns: ['乾燥', '毛穴', 'シミ・くすみ', 'ハリ・たるみ', '敏感肌'],
    images: [],
    sortOrder: 1,
    isActive: true,
  },
  {
    id: '2',
    slug: 'cleansing',
    name: 'ミトコンドリアのちから',
    subtitle: 'クレンジング',
    description: 'メイクも毛穴汚れも、するんと落とす。ミトコンドリア活性成分配合のクレンジングジェル。洗い上がりはしっとり、つっぱりません。',
    category: 'single',
    price: 5280,
    subscriptionPrice: 4752,
    subscriptionDiscountPct: 10,
    volume: '180ml',
    usageDuration: '約2ヶ月',
    ingredients: 'シリカ水、ヤシ油脂肪酸、グリセリン、ミトコンドリア活性成分配合',
    features: [
      'ジェルタイプで肌に優しい',
      'ダブル洗顔不要',
      '毛穴汚れもすっきり',
      'ミトコンドリア活性成分配合',
    ],
    skinConcerns: ['毛穴', '敏感肌'],
    images: [],
    sortOrder: 2,
    isActive: true,
  },
  {
    id: '3',
    slug: 'soap',
    name: 'ミトコンドリアのちから',
    subtitle: 'ソープ',
    description: '豊かな泡立ちで、やさしく洗い上げる固形ソープ。ミトコンドリア活性成分とケイ素を配合し、洗うたびに肌を整えます。',
    category: 'single',
    price: 3960,
    subscriptionPrice: 3564,
    subscriptionDiscountPct: 10,
    volume: '80g',
    usageDuration: '約2ヶ月',
    ingredients: '石ケン素地、シリカ、グリセリン、ミトコンドリア活性成分配合',
    features: [
      '濃密泡でやさしく洗う',
      'ケイ素配合の洗顔ソープ',
      '洗い上がりしっとり',
      '全身にも使用可能',
    ],
    skinConcerns: ['乾燥', '毛穴', '敏感肌'],
    images: [],
    sortOrder: 3,
    isActive: true,
  },
  {
    id: '4',
    slug: 'sample',
    name: '14日間サンプルセット',
    subtitle: 'お試しセット',
    description: 'アキノリオの引き算スキンケアを14日間じっくりお試しいただけるサンプルセットです。美容液・クレンジング・ソープの3点セット。',
    category: 'set',
    price: 0,
    subscriptionPrice: 0,
    subscriptionDiscountPct: 0,
    volume: '14日分',
    usageDuration: '14日間',
    ingredients: '',
    features: [
      '美容液・クレンジング・ソープの3点セット',
      '14日間じっくり試せる',
      '送料無料',
      'LINE登録で使い方サポート付き',
    ],
    skinConcerns: ['乾燥', '毛穴', 'シミ・くすみ', 'ハリ・たるみ', '敏感肌'],
    images: [],
    sortOrder: 0,
    isActive: true,
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'M.T',
    age: 52,
    skinConcern: 'ハリ・たるみ',
    content: '使い始めて1ヶ月で、朝起きた時の肌のハリが全然違うことに気づきました。引き算のスキンケアという考え方に最初は半信半疑でしたが、今では手放せません。',
    rating: 5,
    productName: 'ミトコンドリアのちから 美容液',
  },
  {
    id: '2',
    name: 'K.S',
    age: 45,
    skinConcern: '毛穴',
    content: '長年悩んでいた毛穴の開きが、3ヶ月使い続けたら目立たなくなってきました。友人からも「何か変えた？」と聞かれるようになりました。',
    rating: 5,
    productName: 'ミトコンドリアのちから 美容液',
  },
  {
    id: '3',
    name: 'Y.N',
    age: 38,
    skinConcern: '敏感肌',
    content: 'アトピー体質で化粧品選びにはとても慎重ですが、アキノリオは全く刺激がなく安心して使えています。肌が本来の力を取り戻していく感覚があります。',
    rating: 5,
    productName: 'ミトコンドリアのちから 美容液',
  },
  {
    id: '4',
    name: 'R.M',
    age: 61,
    skinConcern: 'シミ・くすみ',
    content: 'くすみが気になっていましたが、使い続けるうちにワントーン明るくなった気がします。年齢を言うと驚かれることが増えました。',
    rating: 5,
    productName: 'ミトコンドリアのちから 美容液',
  },
]

export const PREFECTURES = [
  '北海道', '青森県', '岩手県', '宮城県', '秋田県', '山形県', '福島県',
  '茨城県', '栃木県', '群馬県', '埼玉県', '千葉県', '東京都', '神奈川県',
  '新潟県', '富山県', '石川県', '福井県', '山梨県', '長野県',
  '岐阜県', '静岡県', '愛知県', '三重県',
  '滋賀県', '京都府', '大阪府', '兵庫県', '奈良県', '和歌山県',
  '鳥取県', '島根県', '岡山県', '広島県', '山口県',
  '徳島県', '香川県', '愛媛県', '高知県',
  '福岡県', '佐賀県', '長崎県', '熊本県', '大分県', '宮崎県', '鹿児島県', '沖縄県',
]
