import type { Product, Testimonial } from '@/types'

export const SITE_NAME = 'AKINORIO'
export const SITE_URL = 'https://akinorio.com'
export const SITE_DESCRIPTION = '何をつけるかより、何をやめるか。ミトコンドリア×ケイ素の力で、肌のOSを初期化する引き算のスキンケア。'
export const LINE_URL = 'https://lin.ee/qF2bQ2v'
export const FREE_SHIPPING_THRESHOLD = 10000
export const SHIPPING_FEE = 600

export const PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'serum',
    name: 'ミトコンドリアのちから',
    subtitle: '細胞美容液',
    description: '原料メーカーが「これだけの配合量は美容液と呼んでください」と言った一本。ファンデーションも化粧水もいらない。ダブル洗顔も不要。最終的にこの一本で済む素肌へ導くために生まれた、引き算のスキンケアの核心。ミトコンドリアとケイ素の力で、細胞が自ら美しくなる力を呼び覚まします。',
    category: 'single',
    price: 13200,
    subscriptionPrice: 11880,
    subscriptionDiscountPct: 10,
    volume: '50g',
    usageDuration: '約3ヶ月',
    ingredients: 'シリカ水、スクワラン、ホホバ種子油、ミトコンドリア活性成分配合',
    features: [
      'ミトコンドリア活性化テクノロジー',
      'ケイ素（シリカ）配合',
      'パラベンフリー・アルコールフリー',
      '敏感肌にも使える低刺激処方',
      '1本で約3ヶ月使用可能',
    ],
    skinConcerns: ['乾燥', '毛穴', 'シミ・くすみ', 'ハリ・たるみ', '敏感肌'],
    images: [],
    sortOrder: 1,
    isActive: true,
  },
  {
    id: '2',
    slug: 'cleansing',
    name: 'ミトコンドリアのちから',
    subtitle: 'クレンジング',
    description: 'ダブル洗顔という「余計な儀式」を終わらせるクレンジング。メイクも毛穴汚れも、するんと落とす。ミトコンドリア活性成分を配合し、落とすたびに肌が整っていく。洗い上がりはしっとり、つっぱりません。引き算の第一歩は、ここから。',
    category: 'single',
    price: 5280,
    subscriptionPrice: 4752,
    subscriptionDiscountPct: 10,
    volume: '180ml',
    usageDuration: '約2ヶ月',
    ingredients: 'シリカ水、ヤシ油脂肪酸、グリセリン、ミトコンドリア活性成分配合',
    features: [
      'ジェルタイプで肌に優しい',
      'ダブル洗顔不要',
      '毛穴汚れもすっきり',
      'ミトコンドリア活性成分配合',
    ],
    skinConcerns: ['毛穴', '敏感肌'],
    images: [],
    sortOrder: 2,
    isActive: true,
  },
  {
    id: '3',
    slug: 'soap',
    name: 'ミトコンドリアのちから',
    subtitle: 'ソープ',
    description: '工場が「30年の歴史で、こんな形状を作ったのは初めて」と言った石鹸。豊かな泡立ちで、やさしく洗い上げる。ミトコンドリア活性成分とケイ素を配合し、洗うたびに肌本来の力を呼び覚ます。朝は水洗顔すら不要になる、その日のために。',
    category: 'single',
    price: 3960,
    subscriptionPrice: 3564,
    subscriptionDiscountPct: 10,
    volume: '80g',
    usageDuration: '約2ヶ月',
    ingredients: '石ケン素地、シリカ、グリセリン、ミトコンドリア活性成分配合',
    features: [
      '濃密泡でやさしく洗う',
      'ケイ素配合の洗顔ソープ',
      '洗い上がりしっとり',
      '全身にも使用可能',
    ],
    skinConcerns: ['乾燥', '毛穴', '敏感肌'],
    images: [],
    sortOrder: 3,
    isActive: true,
  },
  {
    id: '4',
    slug: 'sample',
    name: '14日間 引き算プログラム',
    subtitle: '体験セット',
    description: 'あなたの肌と、出会い直す14日間。余計なケアをやめたとき、肌は何を語り始めるのか。美容液・クレンジング・ソープの3点で、引き算のスキンケアを体感してください。',
    category: 'set',
    price: 0,
    subscriptionPrice: 0,
    subscriptionDiscountPct: 0,
    volume: '14日分',
    usageDuration: '14日間',
    ingredients: '',
    features: [
      '美容液・クレンジング・ソープの3点セット',
      '14日間の引き算プログラム',
      '送料は当方が負担いたします',
      'LINEで引き算スキンケアのヒントをお届け',
    ],
    skinConcerns: ['乾燥', '毛穴', 'シミ・くすみ', 'ハリ・たるみ', '敏感肌'],
    images: [],
    sortOrder: 0,
    isActive: true,
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'M.T',
    age: 52,
    skinConcern: 'ハリ・たるみ',
    content: '引き算を始めて1ヶ月。朝、鏡を見て涙が出ました。何十年も「足す」ことばかりしていた自分が恥ずかしくなるほど、肌が生き返っていた。もっと早く出会いたかった。この感動を、同じ悩みを持つ友人にも伝えました。',
    rating: 5,
    productName: 'ミトコンドリアのちから 美容液',
  },
  {
    id: '2',
    name: 'K.S',
    age: 45,
    skinConcern: '毛穴',
    content: '長年の毛穴の悩みが、引き算を始めて3ヶ月で嘘のように落ち着きました。化粧水を重ねて、美容液を重ねて、クリームを重ねて。あの「足し算の日々」は一体何だったのか。救われた気持ちです。友人にも教えたくて、もう3人に紹介しました。',
    rating: 5,
    productName: 'ミトコンドリアのちから 美容液',
  },
  {
    id: '3',
    name: 'Y.N',
    age: 38,
    skinConcern: '敏感肌',
    content: 'アトピー体質で、何を塗っても赤くなる肌でした。皮膚科で処方された薬すら合わないこともあった。でもアキノリオだけは違った。全く刺激がなく、肌が本来の力を取り戻していくのを感じました。本当に救われました。',
    rating: 5,
    productName: 'ミトコンドリアのちから 美容液',
  },
  {
    id: '4',
    name: 'R.M',
    age: 61,
    skinConcern: 'シミ・くすみ',
    content: '60歳を過ぎて「もう何をしても」と諦めていました。でも引き算を始めてから、肌が自ら明るさを取り戻していく。ファンデーションなしで外出できる日が来るなんて。娘に「お母さん、肌きれいになった」と言われた時、泣きそうになりました。',
    rating: 5,
    productName: 'ミトコンドリアのちから 美容液',
  },
]

export const PREFECTURES = [
  '北海道', '青森県', '岩手県', '宮城県', '秋田県', '山形県', '福島県',
  '茨城県', '栃木県', '群馬県', '埼玉県', '千葉県', '東京都', '神奈川県',
  '新潟県', '富山県', '石川県', '福井県', '山梨県', '長野県',
  '岐阜県', '静岡県', '愛知県', '三重県',
  '滋賀県', '京都府', '大阪府', '兵庫県', '奈良県', '和歌山県',
  '鳥取県', '島根県', '岡山県', '広島県', '山口県',
  '徳島県', '香川県', '愛媛県', '高知県',
  '福岡県', '佐賀県', '長崎県', '熊本県', '大分県', '宮崎県', '鹿児島県', '沖縄県',
]
